# Generated by Django 5.0.6 on 2024-06-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cuit',
            field=models.CharField(default='', max_length=11, verbose_name='CUIT'),
        ),
    ]
