# Generated by Django 5.0.6 on 2024-06-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0002_company_cuit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cuit',
            field=models.CharField(default='', max_length=13, verbose_name='CUIT'),
        ),
    ]
