# Generated by Django 5.0.6 on 2024-06-10 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['item_order'], 'verbose_name': 'ítem', 'verbose_name_plural': 'ítems'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['option_order'], 'verbose_name': 'opción', 'verbose_name_plural': 'opciones'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-updated', 'question_order'], 'verbose_name': 'pregunta', 'verbose_name_plural': 'preguntas'},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='order',
            new_name='item_order',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='order',
            new_name='option_order',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='order',
            new_name='question_order',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='order',
            new_name='section_order',
        ),
    ]
