# Generated by Django 5.0.6 on 2024-06-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_item_options_alter_option_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.CharField(max_length=500, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='section',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Texto'),
        ),
    ]
