# Generated by Django 5.0.6 on 2024-06-20 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_type_alter_question_options_alter_section_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='questions.type', verbose_name='Tipo'),
        ),
    ]
