# Generated by Django 5.0.6 on 2024-06-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_delete_type_rename_type_question_question_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='nombre')),
                ('description', models.CharField(max_length=500, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación')),
            ],
            options={
                'verbose_name': 'Tipo de pregunta',
                'verbose_name_plural': 'Tipos de pregunta',
                'ordering': ['name'],
            },
        ),
    ]
