# Generated by Django 5.0.6 on 2024-06-24 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_survey_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='survey_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='questions.survey_type', verbose_name='Tipo de Encuesta'),
        ),
    ]
