# Generated by Django 5.0.6 on 2024-06-24 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_remove_question_survey_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='survey_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='questions.survey_type', verbose_name='Tipo de Encuesta'),
        ),
    ]
