# Generated by Django 5.0.6 on 2024-06-24 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_section_survey_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='content',
            new_name='text',
        ),
    ]
