# Generated by Django 5.0.6 on 2024-06-24 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_rename_content_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='questions.question', verbose_name='Pregunta'),
        ),
        migrations.AlterField(
            model_name='option',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='questions.item', verbose_name='Item'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_order', models.IntegerField(verbose_name='Orden')),
                ('text', models.CharField(max_length=500, verbose_name='Texto')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación')),
                ('item', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='questions.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'nota',
                'verbose_name_plural': 'notas',
                'ordering': ['note_order'],
            },
        ),
    ]
