# Generated by Django 5.0.6 on 2024-06-24 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_alter_item_question_alter_option_item_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Texto')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación')),
                ('question', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='questions.question', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'subtítulo',
                'verbose_name_plural': 'subtítulos',
                'ordering': ['-updated'],
            },
        ),
    ]
