# Generated by Django 5.0.6 on 2024-06-25 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='item',
        ),
        migrations.AddField(
            model_name='note',
            name='option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='questions.option', verbose_name='Option'),
        ),
    ]
