# Generated by Django 5.0.6 on 2024-07-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_remove_note_item_note_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey_type',
            name='year',
            field=models.IntegerField(default=2024, verbose_name='año'),
            preserve_default=False,
        ),
    ]
