# Generated by Django 5.0.6 on 2024-07-24 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_alter_subtitle_options_remove_item_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['number'], 'verbose_name': 'pregunta', 'verbose_name_plural': 'preguntas'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_order',
        ),
    ]
