# Generated by Django 5.0.6 on 2024-07-24 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_alter_question_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitle',
            name='question',
        ),
    ]
