# Generated by Django 5.0.6 on 2024-07-25 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_remove_subtitle_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subtitle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='questions.subtitle', verbose_name='Subtítulo'),
        ),
    ]
