# Generated by Django 5.0.6 on 2024-07-25 15:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_question_subtitle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subtitle',
            new_name='Subsection',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='subtitle',
            new_name='subsection',
        ),
    ]
