# Generated by Django 5.0.6 on 2024-08-06 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_rename_subtitle_subsection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='questions.option'),
        ),
    ]
