# Generated by Django 5.0.6 on 2024-08-07 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0022_option_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='parent',
        ),
        migrations.AddField(
            model_name='option',
            name='children',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='questions.item'),
        ),
    ]
