# Generated by Django 5.0.6 on 2024-08-07 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0023_remove_option_parent_option_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='Pregunta'),
        ),
    ]
