# Generated by Django 5.0.6 on 2024-08-07 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0024_alter_item_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['code'], 'verbose_name': 'opción', 'verbose_name_plural': 'opciones'},
        ),
        migrations.RenameField(
            model_name='option',
            old_name='option_order',
            new_name='code',
        ),
    ]
