# Generated by Django 5.0.6 on 2024-08-30 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0026_filter_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filter_Type',
        ),
    ]
