# Generated by Django 5.0.6 on 2024-07-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supervisor',
            options={'ordering': ['SUP_CODE'], 'verbose_name': 'supervisor', 'verbose_name_plural': 'supervisores'},
        ),
        migrations.AlterModelOptions(
            name='surveyor',
            options={'ordering': ['ENC_CODE'], 'verbose_name': 'encuestador', 'verbose_name_plural': 'encuestadores'},
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='SUP_CODE',
            field=models.IntegerField(verbose_name='Código de Supervisor'),
        ),
    ]
