# Generated by Django 5.0.6 on 2024-07-20 03:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_supervisor_options_alter_surveyor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervisor',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación'),
        ),
        migrations.AddField(
            model_name='surveyor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyor',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación'),
        ),
    ]
