# Generated by Django 5.0.6 on 2024-07-21 21:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_supervisor_created_supervisor_updated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='created',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='surveyor',
            name='created',
        ),
        migrations.RemoveField(
            model_name='surveyor',
            name='updated',
        ),
        migrations.AddField(
            model_name='supervisor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado el'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervisor',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervisor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado el'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_updated_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado el'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyor',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='surveyor_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado el'),
        ),
        migrations.AddField(
            model_name='surveyor',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='surveyor_updated_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
            preserve_default=False,
        ),
    ]
