# Generated by Django 5.0.6 on 2024-06-15 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('questions', '0003_alter_item_text_alter_option_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('company', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'encuesta',
                'verbose_name_plural': 'encuestas',
                'ordering': ['-updated', 'company'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500, verbose_name='Valor')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('option', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='questions.option', verbose_name='Opción')),
                ('survey', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='surveys.survey', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'respuesta',
                'verbose_name_plural': 'respuestas',
                'ordering': ['survey', '-updated'],
            },
        ),
    ]
