# Generated by Django 5.0.6 on 2024-06-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_survey_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Survey_Type',
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_type',
            field=models.IntegerField(default=1, verbose_name='Tipo de Encuesta'),
            preserve_default=False,
        ),
    ]
