# Generated by Django 5.0.6 on 2024-06-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_alter_survey_survey_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_type',
            field=models.IntegerField(verbose_name='Tipo de Encuesta'),
        ),
    ]
