# Generated by Django 5.0.6 on 2024-06-28 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_survey_progress_survey_survey_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey_state',
            options={'ordering': ['name'], 'verbose_name': 'Estado de la encuesta', 'verbose_name_plural': 'Estados de la encuesta'},
        ),
    ]
