# Generated by Django 5.0.6 on 2024-06-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_alter_survey_state_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='progress',
            field=models.IntegerField(default=1, verbose_name='Progreso'),
        ),
    ]
