# Generated by Django 5.0.6 on 2024-07-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_alter_survey_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='progress',
            field=models.IntegerField(default=1, verbose_name='Progreso'),
        ),
    ]
