# Generated by Django 5.0.6 on 2024-07-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_alter_survey_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='number_of_questions',
            field=models.IntegerField(default=1, verbose_name='Cantidad de preguntas'),
            preserve_default=False,
        ),
    ]
