# Generated by Django 5.0.6 on 2024-07-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0014_alter_survey_number_of_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='next_question',
            field=models.IntegerField(default=1, verbose_name='Pregunta siguiente'),
        ),
    ]
