# Generated by Django 5.0.6 on 2024-07-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0015_survey_next_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='next_question',
            field=models.IntegerField(default=0, verbose_name='Pregunta siguiente'),
        ),
    ]
