# Generated by Django 5.0.6 on 2024-08-28 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0025_alter_option_options_rename_option_order_option_code'),
        ('surveys', '0022_variable_list_variable_variable_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey_Remaining_Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado el')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregunta_pendiente_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('question', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='questions.question', verbose_name='Pregunta')),
                ('survey', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='surveys.survey', verbose_name='Empresa')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregunta_pendiente_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'respuesta',
                'verbose_name_plural': 'respuestas',
                'ordering': ['survey', '-updated_at'],
            },
        ),
    ]
