# Generated by Django 5.0.6 on 2024-08-28 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0023_survey_remaining_questions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey_remaining_questions',
            options={'ordering': ['survey', 'question'], 'verbose_name': 'preguntas restantes de encuesta', 'verbose_name_plural': 'preguntas restantes de encuesta'},
        ),
    ]
