# Generated by Django 5.0.6 on 2024-08-29 23:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0025_alter_option_options_rename_option_order_option_code'),
        ('surveys', '0024_alter_survey_remaining_questions_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Survey_Remaining_Questions',
            new_name='Survey_Questions',
        ),
    ]
