# Generated by Django 5.0.6 on 2024-08-29 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0027_alter_survey_question_state_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey_questions',
            name='survey_question_state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='surveys.survey_question_state', verbose_name='Estado de la pregunta'),
            preserve_default=False,
        ),
    ]
