# Generated by Django 5.0.6 on 2024-08-30 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0029_filter_filter_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='filter_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='surveys.filter_type', verbose_name='Tipo de filtro'),
            preserve_default=False,
        ),
    ]
