# Generated by Django 5.0.6 on 2024-08-30 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0030_filter_filter_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filter',
            options={'ordering': ['question'], 'verbose_name': 'Filtro', 'verbose_name_plural': 'Filtros'},
        ),
        migrations.AlterModelOptions(
            name='filter_type',
            options={'ordering': ['name'], 'verbose_name': 'Tipo de filtro', 'verbose_name_plural': 'Tipos de filtro'},
        ),
    ]
