# Generated by Django 5.0.6 on 2024-08-30 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0033_filter_dest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filter',
            old_name='variables',
            new_name='variable',
        ),
    ]
