# Generated by Django 5.0.6 on 2024-08-31 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0036_filter_condition_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filter',
            old_name='variable',
            new_name='variables',
        ),
    ]
