# Generated by Django 5.0.6 on 2024-08-31 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0037_rename_variable_filter_variables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='variables',
        ),
        migrations.AddField(
            model_name='filter',
            name='variables',
            field=models.ManyToManyField(to='surveys.variable_list', verbose_name='Variables'),
        ),
    ]
