# Generated by Django 5.0.6 on 2024-09-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0038_remove_filter_variables_filter_variables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition_type',
            name='symbol',
            field=models.CharField(max_length=2, verbose_name='símbolo'),
        ),
    ]
