# Generated by Django 5.0.6 on 2024-09-16 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0027_delete_filter_type'),
        ('surveys', '0039_alter_condition_type_symbol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Validationjs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nombre')),
                ('value', models.IntegerField(verbose_name='Valor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado el')),
                ('condition_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='surveys.condition_type', verbose_name='Condición')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validationjs_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questions.question', verbose_name='pregunta')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validationjs_updated_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Validación JS',
                'verbose_name_plural': 'Validaciones JS',
                'ordering': ['name'],
            },
        ),
    ]
