# Generated by Django 5.0.6 on 2024-08-03 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_city_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companies.district', verbose_name='Departamento'),
        ),
    ]
