# Generated by Django 5.0.6 on 2024-08-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_company_web_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='web_page',
            field=models.CharField(default=1, verbose_name='Página web'),
            preserve_default=False,
        ),
    ]
