# Generated by Django 5.0.7 on 2024-09-17 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='code',
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(default=94, on_delete=django.db.models.deletion.DO_NOTHING, to='companies.state', verbose_name='Provincia'),
            preserve_default=False,
        ),
    ]
