# Generated by Django 5.0.7 on 2024-09-17 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_remove_district_code_district_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'localidad', 'verbose_name_plural': 'localidades'},
        ),
        migrations.AddField(
            model_name='city',
            name='district',
            field=models.ForeignKey(default=94011, on_delete=django.db.models.deletion.DO_NOTHING, to='companies.district', verbose_name='Departamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='code',
            field=models.IntegerField(max_length=8, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
    ]
