# Generated by Django 5.0.7 on 2024-09-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_alter_city_options_city_district_alter_city_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='code',
            field=models.IntegerField(verbose_name='Código'),
        ),
    ]
