# Generated by Django 5.0.7 on 2024-09-17 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_alter_city_code'),
        ('team', '0004_remove_supervisor_created_remove_supervisor_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='due_id',
            field=models.IntegerField(default=0, verbose_name='Valor del campo ID en DUE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='inactive',
            field=models.BooleanField(default=False, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='original_id',
            field=models.IntegerField(default=0, verbose_name='ID original'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='team.supervisor', verbose_name='Supervisor Asignado'),
        ),
        migrations.AddField(
            model_name='company',
            name='year',
            field=models.IntegerField(default=2024, verbose_name='Año del operativo'),
            preserve_default=False,
        ),
    ]
