# Generated by Django 5.0.6 on 2024-09-18 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_company_due_id_company_inactive_company_original_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='district',
        ),
        migrations.RemoveField(
            model_name='company',
            name='supervisor',
        ),
    ]
