# Generated by Django 5.0.7 on 2024-09-18 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_remove_company_district_remove_company_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='dept',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='company',
            name='floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Piso'),
        ),
        migrations.AddField(
            model_name='company',
            name='sector',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número / Km'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Calle / Ruta'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companies.city', verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='company',
            name='original_id',
            field=models.IntegerField(default=0, verbose_name='ID original'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='company',
            name='web_page',
            field=models.CharField(blank=True, null=True, verbose_name='Página web'),
        ),
        migrations.AlterField(
            model_name='company',
            name='zip_code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Código Postal'),
        ),
    ]
