# Generated by Django 5.0.7 on 2024-09-18 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_company_dept_company_floor_company_sector_and_more'),
        ('team', '0004_remove_supervisor_created_remove_supervisor_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='surveyor',
        ),
        migrations.AddField(
            model_name='company',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='team.supervisor', verbose_name='Supervisor Asignado'),
        ),
    ]
