# Generated by Django 5.0.7 on 2024-09-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_remove_company_surveyor_company_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='clanae_code',
        ),
        migrations.AddField(
            model_name='company',
            name='activity_code',
            field=models.CharField(default=0, max_length=2, verbose_name='Código de Actividad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='address_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número / Km'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cuit',
            field=models.CharField(default='', max_length=11, verbose_name='CUIT'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='company',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código Postal'),
        ),
    ]
