# Generated by Django 5.0.7 on 2024-09-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_remove_company_clanae_code_company_activity_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='inactive',
            field=models.BooleanField(verbose_name='Inactivo'),
        ),
    ]
