# Generated by Django 5.0.6 on 2024-06-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.IntegerField(default=1, verbose_name='Tipo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='survey_type',
            field=models.IntegerField(default=1, verbose_name='Tipo de Encuesta'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
