# Generated by Django 5.0.6 on 2024-06-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_survey_type_alter_question_survey_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='survey_type',
            field=models.IntegerField(verbose_name='Tipo de Encuesta'),
        ),
    ]
